name: Branch deploy test
on:
  issue_comment:
    types: [created] # Add "deploy test" as a PR comment to trigger this workflow.

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    environment: "deploy_test"
    permissions:
      pull-requests: write # Required for commenting on PRs
      deployments: write # Required for updating deployment statuses
      contents: write # Required for reading/writing the lock file
      checks: read # Required for checking if the CI checks have passed in order to deploy the PR
      statuses: read # Required for checking if all commit statuses are "success" in order to deploy the PR
    outputs:
      success: ${{ steps.create_matrix.outputs.prepare_success }}
      sha: ${{ steps.branch-deploy.outputs.sha }}
    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v12.0.0
        with:
          trigger: "deploy test"
          reaction: "eyes"
          stable_branch: "main"
          update_branch: "disabled" # do not require the branch to be up-to-date

      - name: debug
        run: |
          echo decision ${{ steps.branch-deploy.outputs.decision }}
          echo reason_code ${{ steps.branch-deploy.outputs.reason_code }}
          echo result ${{ steps.branch-deploy.outputs.result }}
          echo continue ${{ steps.branch-deploy.outputs.continue }}
          echo fork ${{ steps.branch-deploy.outputs.fork }}
          echo triggered ${{ steps.branch-deploy.outputs.triggered }}
          echo comment_body ${{ steps.branch-deploy.outputs.comment_body }}
          echo issue_number ${{ steps.branch-deploy.outputs.issue_number }}
          echo actor ${{ steps.branch-deploy.outputs.actor }}
          echo environment ${{ steps.branch-deploy.outputs.environment }}
          echo params ${{ steps.branch-deploy.outputs.params }}
          echo parsed_params ${{ steps.branch-deploy.outputs.parsed_params }}
          echo noop ${{ steps.branch-deploy.outputs.noop }}
          echo sha ${{ steps.branch-deploy.outputs.sha }}
          echo default_branch_tree_sha ${{ steps.branch-deploy.outputs.default_branch_tree_sha }}
          echo ref ${{ steps.branch-deploy.outputs.ref }}
          echo base_ref ${{ steps.branch-deploy.outputs.base_ref }}
          echo comment_id ${{ steps.branch-deploy.outputs.comment_id }}
          echo deployment_id ${{ steps.branch-deploy.outputs.deployment_id }}
          echo environment_url ${{ steps.branch-deploy.outputs.environment_url }}
          echo type ${{ steps.branch-deploy.outputs.type }}
          echo fork_ref ${{ steps.branch-deploy.outputs.fork_ref }}
          echo fork_label ${{ steps.branch-deploy.outputs.fork_label }}
          echo fork_checkout ${{ steps.branch-deploy.outputs.fork_checkout }}
          echo fork_full_name ${{ steps.branch-deploy.outputs.fork_full_name }}
          echo initial_reaction_id ${{ steps.branch-deploy.outputs.initial_reaction_id }}
          echo initial_comment_id ${{ steps.branch-deploy.outputs.initial_comment_id }}
          echo actor_handle ${{ steps.branch-deploy.outputs.actor_handle }}
          echo global_lock_claimed ${{ steps.branch-deploy.outputs.global_lock_claimed }}
          echo global_lock_released ${{ steps.branch-deploy.outputs.global_lock_released }}
          echo unlocked_environments ${{ steps.branch-deploy.outputs.unlocked_environments }}
          echo sha_deployment ${{ steps.branch-deploy.outputs.sha_deployment }}
          echo review_decision ${{ steps.branch-deploy.outputs.review_decision }}
          echo is_outdated ${{ steps.branch-deploy.outputs.is_outdated }}
          echo merge_state_status ${{ steps.branch-deploy.outputs.merge_state_status }}
          echo commit_status ${{ steps.branch-deploy.outputs.commit_status }}
          echo approved_reviews_count ${{ steps.branch-deploy.outputs.approved_reviews_count }}
          echo needs_to_be_deployed ${{ steps.branch-deploy.outputs.needs_to_be_deployed }}
          echo commit_verified ${{ steps.branch-deploy.outputs.commit_verified }}
          echo total_seconds ${{ steps.branch-deploy.outputs.total_seconds }}
          echo non_default_target_branch_used ${{ steps.branch-deploy.outputs.non_default_target_branch_used }}

      - name: checkout
        if: steps.branch-deploy.outputs.continue == 'true'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ steps.branch-deploy.outputs.sha }}

      - name: update date
        if: steps.branch-deploy.outputs.continue == 'true'
        id: create_matrix
        run: |
          date >> timestamp.txt
          echo "prepare_success=true" >> $GITHUB_OUTPUT

  update:
    needs: [prepare]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    if: ${{ needs.prepare.outputs.success }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ needs.prepare.outputs.sha }}

      - name: Print
        run: |
          echo xxx ${{ needs.prepare.outputs.success }} yyy
          echo xxx ${{ needs.prepare.outputs.sha }} yyy
          git log -2
          git status
