name: Branch deploy test
on:
  issue_comment:
    types: [created] # Add "deploy test" as a PR comment to trigger this workflow.

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required for commenting on PRs
      deployments: write # Required for updating deployment statuses
      contents: write # Required for reading/writing the lock file
      checks: read # Required for checking if the CI checks have passed in order to deploy the PR
      statuses: read # Required for checking if all commit statuses are "success" in order to deploy the PR
    outputs:
      success: ${{ steps.create_matrix.outputs.prepare_success }}
      sha: ${{ steps.branch-deploy.outputs.sha }}
    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v12.0.0
        with:
          trigger: "deploy test"
          reaction: "eyes"
          stable_branch: "main"
          update_branch: "disabled" # do not require the branch to be up-to-date
          environment: "deploy_test"

      - name: checkout
        if: steps.branch-deploy.outputs.continue == 'true'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ steps.branch-deploy.outputs.sha }}

      - name: update date
        if: steps.branch-deploy.outputs.continue == 'true'
        id: create_matrix
        run: |
          date >> timestamp.txt
          echo "prepare_success=true" >> $GITHUB_OUTPUT

  update:
    needs: [prepare]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    if: ${{ needs.prepare.outputs.success }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ needs.prepare.outputs.sha }}

      - name: Print
        run: |
          echo xxx ${{ needs.prepare.outputs.success }} yyy
          echo xxx ${{ needs.prepare.outputs.sha }} yyy
          git log -2
          git status
