name: Test001 Comment

on:
  issue_comment:
    types: [created]  # Add "Test001" as a PR comment to trigger.

jobs:
  doit:
    runs-on: ubuntu-latest
    permissions:
      # Permissions for the branch-deploy action, as documented here:
      #  https://github.com/github/branch-deploy#how-does-it-work-
      pull-requests: write # Required for commenting on PRs
      deployments: write # Required for updating deployment statuses
      contents: write # Required for reading/writing the lock file
      checks: read # Required for checking if the CI checks have passed in order to deploy the PR
      statuses: read # Required for checking if all commit statuses are "success" in order to deploy the PR

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@f0984057ffe1aa340aa017b6eafb894310aed88e # v12.0.0
        with:
          trigger: "Test001"
          reaction: "eyes"
          stable_branch: "dev"
          checks: "required" # don't proceed if any required checks failed
          environment: "Test001"

      - name: call reusuable workflow
        if: steps.branch-deploy.outputs.continue == 'true'
        uses: $/.github/workflows/callee001.yml
        with:
          pr_id: ${{ github.event.issue.number }}
          sha: ${{ steps.branch-deploy.outputs.sha }}
