name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name for release'
        required: true

env:
  testvar:
    name: testpypi
    url: https://test.pypi.org/p/seclab-taskflow-agent2

jobs:
  publish:
    name: Publish wheel to TestPyPI
    permissions:
      contents: write
      id-token: write  # For trusted publishing
    strategy:
      matrix:
        name: [testpypi]
        url: [https://test.pypi.org/p/seclab-taskflow-agent2]
    uses: ./.github/workflows/publish-reusable.yml
    with:
      tag_name: ${{ inputs.version }}
      release_notes: ${{ github.head_ref }}
      repository_url: https://test.pypi.org/legacy/
      environment: ${{ toJSON(matrix) }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
