name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name for release'
        required: true

jobs:
  publish:
    name: Publish wheel to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # For trusted publishing
    steps:
      - name: Create env
        run: echo hi

      - name: Do it
        uses: ./.github/workflows/publish-reusable.yml
        with:
          tag_name: ${{ inputs.version }}
          release_notes: ${{ github.head_ref }}
          repository_url: https://test.pypi.org/legacy/
          environment: wassup
        secrets:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
