name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name for release'
        required: true

jobs:
  create_tag_name:
    name: Create Environment
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag_name.outputs.tag_name }}
    steps:
      - name: Build
        id: create_tag_name_step
        env:
          REFNAME: ${{ github.head_ref }}
        run: echo "tag_name=$REFNAME" >> $GITHUB_OUTPUT

  publish:
    name: Publish wheel to TestPyPI
    needs: create_tag_name
    permissions:
      contents: write
      id-token: write  # For trusted publishing
    uses: ./.github/workflows/publish-reusable.yml
    with:
      tag_name: ${{ inputs.version }}
      release_notes: ${{ github.head_ref }}
      repository_url: https://test.pypi.org/legacy/
      environment: ${{ needs.create_tag_name.outputs.tag_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
