name: Test002 on push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  doit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: kevinbackhouse/actions-experiments/.github/actions/Test002@main
