name: Test002

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  doit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: ./.github/actions/Test002
